# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Harshit Mittal
tagline:          'Curious Introvert'
description:      'This is a place for me to share thoughts on my day-to-day, travel, coding.'
url:              https://hmit.github.io
baseurl:          /

author:
  name:           'Harshit Mittal'
  url:            https://github.com/hmit

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/hmit/hmit.github.io
