# Plugins
plugins:
  - jekyll-seo-tag
  - jekyll-mentions

# Dependencies
highlighter: rouge

# Permalinks
permalink: pretty

# Setup
title: Harshit
tagline: 'Curious Introvert'
description: 'A place to share my thoughts!'
url: http://127.0.0.1:4000

author:
  name: 'Harshit Mittal'
  github: '@hmit'
  url: https://github.com/hmit

paginate: 5

github:
  repo: https://github.com/hmit/hmit.github.io

origtheme:
  name: hyde
  github: https://github.com/poole/hyde
