# Dependencies
markdown:         redcarpet
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Harshit
tagline:          'Curious Introvert'
description:      'A place for me to share my thoughts'
url:              https://hmit.github.io
baseurl:          https://hmit.github.io/

author:
  name:           'Harshit Mittal'
  url:            https://github.com/hmit

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/hmit/hmit.github.io
